version: "3.9"
services:
  api:
    image: node:20.17.0-alpine
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: [sh, -c, "yarn install && node ace migration:run && node ace db:seed && yarn dev"]
    depends_on:
      - db
      - cache
    networks:
      - db
      - cache
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: track-lyrics
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/docker-data/tracklyric-db:/bitnami/postgresql
    networks:
      - db

  db-hom:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: track-lyrics-hom
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/docker-data/tracklyric-db-hom:/bitnami/postgresql

  cache:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    networks:
      - cache

networks:
  db:

  cache:
